name: Setup (Windows)
description: Install Rust, Bun, and dependencies for Windows runners

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
